name: Clymb Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-20.04 # Explicitly use Ubuntu 20.04 to ensure compatibility with libasound2

    strategy:
      matrix:
        browser: [chrome]  # Currently testing only on Chrome

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium webdriver-manager
          pip install behave

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libxss1 libx11-xcb1 libxcomposite1 libxcursor1 libxi6 libxtst6 \
            libpangocairo-1.0-0 libxrandr2 libatk-bridge2.0-0 libgbm1 libgtk-3-0 \
            libasound2 libasound2-data ttf-mscorefonts-installer
            
          # Install Google Chrome (latest stable version)
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f

      - name: Verify installation and environment
        run: |
          python --version
          pip list
          google-chrome --version || echo "Chrome not found"

      - name: Run Selenium tests
        env:
          BROWSER: ${{ matrix.browser }}
          BASE_URL: ${{ secrets.BASE_URL }} # Securely fetch the URL from GitHub Secrets
          EMAIL: ${{ secrets.EMAIL }} # Securely fetch the email from GitHub Secrets
          PASSWORD: ${{ secrets.PASSWORD }} # Securely fetch the password from GitHub Secrets
          ADMIN_URL: ${{ secrets.ADMIN_URL }} # Securely fetch the URL from GitHub Secrets
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }} # Securely fetch the email from GitHub Secrets
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }} # Securely fetch the password from GitHub Secrets

        run: |
          echo "Running tests on URL: $BASE_URL with browser: $BROWSER"
          if [ "$BROWSER" == "chrome" ]; then
            export DISPLAY=:99.0
            google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
          fi
          pytest --no-capture --no-capture-stderr --format=pretty
